package admin;

import java.awt.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import utilities.*;

public class DPrepTab extends javax.swing.JFrame {
    String s;
    
    String[] temppath;
    String[] tempimgname;
    sqlcon dbconn = new sqlcon();
    Connection connect = null;
    PreparedStatement pstate = null;
    Statement state = null;
    ResultSet resset = null;
    
    //classes
    retrieve_str retstr = new retrieve_str();
    rw_data wrdata = new rw_data();
    writefeatures tstr  = new writefeatures();
    checklist chk = new checklist();
    combo x = new combo();  
    progressbar progbar = new progressbar();
   
    /**
     * Creates new form DatasetPreparationPage
     */
    public DPrepTab(){
        initComponents();
        this.setLocationRelativeTo(null);
        setColor(Panel1, Panel11);
        reset(Panel2,   Panel22);
        reset(Panel3,   Panel33);
        reset(Panel4,   Panel44);
        reset(Panel5,   Panel55);
        showfeat();
        label_username.setText(wrdata.readsession(1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Task = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        Title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label_username = new javax.swing.JLabel();
        NavBar = new javax.swing.JPanel();
        Panel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Panel11 = new javax.swing.JPanel();
        Panel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Panel22 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        Panel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Panel33 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        Panel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Panel44 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        Panel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Panel55 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        Specification = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        combo_grp = new javax.swing.JComboBox();
        btn_browse = new javax.swing.JButton();
        btn_prepare = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Summary = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_summary = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        ImagePrev = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        imgpreview = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Task.setBackground(new java.awt.Color(191, 191, 191));

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("X");
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TaskLayout = new javax.swing.GroupLayout(Task);
        Task.setLayout(TaskLayout);
        TaskLayout.setHorizontalGroup(
            TaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaskLayout.createSequentialGroup()
                .addContainerGap(896, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        TaskLayout.setVerticalGroup(
            TaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskLayout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLayeredPane1.add(Task);
        Task.setBounds(0, 0, 970, 40);

        Title.setBackground(new java.awt.Color(93, 91, 87));
        Title.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Admin Logo.png"))); // NOI18N
        Title.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 58, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CHAID for Skin Lesion");
        Title.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Classification");
        Title.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 161, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Admin Profile.png"))); // NOI18N
        Title.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 50, 60));

        label_username.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        label_username.setForeground(new java.awt.Color(255, 255, 255));
        label_username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_username.setText("John Doe");
        Title.add(label_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, 111, 20));

        jLayeredPane1.add(Title);
        Title.setBounds(0, 40, 970, 80);

        NavBar.setBackground(new java.awt.Color(93, 91, 87));
        NavBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel1.setBackground(new java.awt.Color(132, 131, 113));
        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Dataset Preparation");
        Panel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 37));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Icon DPrep.png"))); // NOI18N
        Panel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 4, 40, 50));

        Panel11.setBackground(new java.awt.Color(255, 179, 123));

        javax.swing.GroupLayout Panel11Layout = new javax.swing.GroupLayout(Panel11);
        Panel11.setLayout(Panel11Layout);
        Panel11Layout.setHorizontalGroup(
            Panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Panel11Layout.setVerticalGroup(
            Panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Panel1.add(Panel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        NavBar.add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 60));

        Panel2.setBackground(new java.awt.Color(93, 91, 87));
        Panel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel2MousePressed(evt);
            }
        });
        Panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("System Training");
        Panel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 37));

        Panel22.setBackground(new java.awt.Color(93, 91, 87));

        javax.swing.GroupLayout Panel22Layout = new javax.swing.GroupLayout(Panel22);
        Panel22.setLayout(Panel22Layout);
        Panel22Layout.setHorizontalGroup(
            Panel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Panel22Layout.setVerticalGroup(
            Panel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Panel2.add(Panel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Icon STest.png"))); // NOI18N
        Panel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 4, 40, 50));

        NavBar.add(Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 230, -1));

        Panel3.setBackground(new java.awt.Color(93, 91, 87));
        Panel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel3MousePressed(evt);
            }
        });
        Panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("System Testing");
        Panel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 37));

        Panel33.setBackground(new java.awt.Color(93, 91, 87));

        javax.swing.GroupLayout Panel33Layout = new javax.swing.GroupLayout(Panel33);
        Panel33.setLayout(Panel33Layout);
        Panel33Layout.setHorizontalGroup(
            Panel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Panel33Layout.setVerticalGroup(
            Panel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Panel3.add(Panel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Icon STrain.png"))); // NOI18N
        Panel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 4, 40, 50));

        NavBar.add(Panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 230, 60));

        Panel4.setBackground(new java.awt.Color(93, 91, 87));
        Panel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel4MousePressed(evt);
            }
        });
        Panel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Report Genertion");
        Panel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 37));

        Panel44.setBackground(new java.awt.Color(93, 91, 87));

        javax.swing.GroupLayout Panel44Layout = new javax.swing.GroupLayout(Panel44);
        Panel44.setLayout(Panel44Layout);
        Panel44Layout.setHorizontalGroup(
            Panel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Panel44Layout.setVerticalGroup(
            Panel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Panel4.add(Panel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Icon RGen.png"))); // NOI18N
        Panel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 4, 40, 50));

        NavBar.add(Panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 230, 60));

        Panel5.setBackground(new java.awt.Color(93, 91, 87));
        Panel5.setAlignmentX(0.0F);
        Panel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel5MousePressed(evt);
            }
        });
        Panel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User Accounts");
        Panel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 37));

        Panel55.setBackground(new java.awt.Color(93, 91, 87));

        javax.swing.GroupLayout Panel55Layout = new javax.swing.GroupLayout(Panel55);
        Panel55.setLayout(Panel55Layout);
        Panel55Layout.setHorizontalGroup(
            Panel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Panel55Layout.setVerticalGroup(
            Panel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Panel5.add(Panel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Icon AMan.png"))); // NOI18N
        Panel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 4, 40, 50));

        NavBar.add(Panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 230, 60));

        jLayeredPane1.add(NavBar);
        NavBar.setBounds(0, 120, 240, 580);

        Body.setBackground(new java.awt.Color(255, 255, 255));
        Body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Specification.setBackground(new java.awt.Color(93, 91, 87));
        Specification.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel6.setText("Dataset Group");

        combo_grp.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        combo_grp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Melanoma Dataset (Training)", "Nevus Dataset (Training)", "Seborrheic Keratosis Dataset (Training)", "Melanoma Dataset (Testing)", "Nevus Dataset (Testing)", "Seborrheic Keratosis Dataset (Testing)" }));
        combo_grp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_browse.setBackground(new java.awt.Color(204, 204, 204));
        btn_browse.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btn_browse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Icon Browse.png"))); // NOI18N
        btn_browse.setText("Browse");
        btn_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_browseActionPerformed(evt);
            }
        });

        btn_prepare.setBackground(new java.awt.Color(30, 144, 255));
        btn_prepare.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btn_prepare.setForeground(new java.awt.Color(255, 255, 255));
        btn_prepare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Icon Prepare.png"))); // NOI18N
        btn_prepare.setText("Prepare");
        btn_prepare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prepareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_browse)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_prepare, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_grp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(combo_grp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_browse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_prepare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        Specification.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 35, 440, 220));

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Specification");
        Specification.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        Body.add(Specification, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 260));

        Summary.setBackground(new java.awt.Color(93, 91, 87));
        Summary.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        table_summary.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        table_summary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Image", "Asymmetry (A)", "Border (B)", "Color (C)", "Diameter (D1)", "Dermoscopic Structure (D2)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_summary.setGridColor(new java.awt.Color(93, 91, 87));
        table_summary.setShowHorizontalLines(false);
        table_summary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_summaryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_summary);
        if (table_summary.getColumnModel().getColumnCount() > 0) {
            table_summary.getColumnModel().getColumn(0).setResizable(false);
            table_summary.getColumnModel().getColumn(1).setResizable(false);
            table_summary.getColumnModel().getColumn(2).setResizable(false);
            table_summary.getColumnModel().getColumn(3).setResizable(false);
            table_summary.getColumnModel().getColumn(4).setResizable(false);
            table_summary.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
        );

        Summary.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 35, 690, 247));

        jLabel21.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Summary");
        Summary.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        Body.add(Summary, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 700, 287));

        ImagePrev.setBackground(new java.awt.Color(93, 91, 87));
        ImagePrev.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        imgpreview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgpreview, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgpreview, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );

        ImagePrev.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 35, 230, 220));

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Image Preview");
        ImagePrev.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        Body.add(ImagePrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 240, 260));

        jLayeredPane1.add(Body);
        Body.setBounds(240, 120, 718, 574);

        jPanel2.setBackground(new java.awt.Color(93, 91, 87));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jLayeredPane1.add(jPanel2);
        jPanel2.setBounds(240, 695, 720, 3);

        jPanel1.setBackground(new java.awt.Color(93, 91, 87));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jLayeredPane1.add(jPanel1);
        jPanel1.setBounds(959, 120, 3, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Panel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel5MousePressed
        new UAccTab().setVisible(true);
    }//GEN-LAST:event_Panel5MousePressed

    private void Panel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel4MousePressed
        new RGenTab().setVisible(true);
    }//GEN-LAST:event_Panel4MousePressed

    private void Panel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel3MousePressed
        new STestTab().setVisible(true);
    }//GEN-LAST:event_Panel3MousePressed

    private void Panel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel2MousePressed
        new STrainTab().setVisible(true);
    }//GEN-LAST:event_Panel2MousePressed

    private void btn_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_browseActionPerformed
        JFileChooser filechooser = new JFileChooser();
        //filechooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        filechooser.setCurrentDirectory(new File("E:\\THESIS\\Dataset - Resized"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","png");
        filechooser.setMultiSelectionEnabled(true);
        filechooser.addChoosableFileFilter(filter);
        int result = filechooser.showSaveDialog(null);
        
        if(result == JFileChooser.APPROVE_OPTION){
            File[] selectedfiles = filechooser.getSelectedFiles();
            temppath = new String[selectedfiles.length];
            tempimgname = new String[selectedfiles.length];
            
            for(int i=0; i<selectedfiles.length; i++){
                temppath[i] = selectedfiles[i].getAbsolutePath();       // E:\THESIS\Dataset\sampleimg\S1.jpg    
                tempimgname[i] = retstr.get_name(temppath[i]);          // S1
            }
        }else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("No Data");
        } 
    }//GEN-LAST:event_btn_browseActionPerformed
 
    private void btn_prepareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prepareActionPerformed
        wrdata.cleartempdata();
        int strint = x.selectcombo_dprep(combo_grp.getSelectedItem().toString());     // retrieve the skin group (0-M;1-N;2-SK)     
        int grp_id = getgrpid(strint);
        int purp_id = getpurpid(strint);
        clear_table();
        insert_multiple(grp_id, purp_id);
        tstr.feature_extract(strint);    
        showfeatfilter(grp_id, purp_id);
        
    }//GEN-LAST:event_btn_prepareActionPerformed
    
    private void table_summaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_summaryMouseClicked
        int i = table_summary.getSelectedRow();
        TableModel fmodel = table_summary.getModel();
        String name = (String)fmodel.getValueAt(i,0);
        int id = tstr.get_imgid(name);
        byte[] byteimg = getImgBlob(id);
        imgpreview.setIcon(ResizeImage(byteimg));
    }//GEN-LAST:event_table_summaryMouseClicked

    private void Panel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Panel2MouseClicked

    private void Panel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel3MouseClicked
        this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_Panel3MouseClicked

    private void Panel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel4MouseClicked
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_Panel4MouseClicked

    private void Panel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel5MouseClicked
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_Panel5MouseClicked
    
    public void insert_multiple(int diag, int pid){
        for(int i=0; i<temppath.length; i++){
            String path = temppath[i];
            String name = tempimgname[i];
             
            //check if image exists in the database. 0 - image exists ; 1 - image does not exist
            if(chk.checkname(name)==0){
                System.out.println(name+" already exists!");
            }else if(chk.checkname(name)==1){
                insert_image(path, name, diag, pid);
                String featimg = retstr.feat_imgname(path);      // S1.jpg
                String featdir = retstr.feat_folderpath(path);   // E:\THESIS\Dataset\sampleimg
                String skngrp = Integer.toString(diag);
                wrdata.writedata(featimg, featdir, skngrp);      // write filename,filedir to tempdata.txt
                JOptionPane.showMessageDialog(null, "Data Inserted!");
            }
        } 
    }
    
    public void insert_image(String path, String name, int strint, int pid){
        connect = dbconn.getConnection();
        int result;
        try{
            String query = "INSERT INTO dataset(img, img_name, img_grp, purp_id) VALUES (?,?,?,?)";
            pstate = connect.prepareStatement(query);
            InputStream is = new FileInputStream(new File(path));
            pstate.setBlob(1, is);
            pstate.setString(2, name);
            pstate.setInt(3, strint);
            pstate.setInt(4, pid);
            result = pstate.executeUpdate();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    public ImageIcon ResizeImage(byte[] imgpath){
        ImageIcon myimage = new ImageIcon(imgpath);
        Image img = myimage.getImage();
        Image newimg = img.getScaledInstance(imgpreview.getWidth(), imgpreview.getHeight(),
                Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newimg);
        return image;
    }
    
    public void showfeatfilter(int gr, int prp){
        ArrayList<Feat> flist = featList(gr, prp);
        DefaultTableModel model = (DefaultTableModel)table_summary.getModel(); 
         Object[] row = new Object[6];
         
         for(int i=0; i<flist.size(); i++){
             row[0] = flist.get(i).getImgName();
             row[1] = flist.get(i).getA();
             row[2] = flist.get(i).getB();
             row[3] = flist.get(i).getC();
             row[4] = flist.get(i).getD1();
             row[5] = flist.get(i).getD2();
             model.addRow(row); 
         }
    }   

    public void showfeat(){
        ArrayList<Feat> flist = featList2();
        DefaultTableModel model = (DefaultTableModel)table_summary.getModel(); 
         Object[] row = new Object[6];
         
         for(int i=0; i<flist.size(); i++){
             row[0] = flist.get(i).getImgName();
             row[1] = flist.get(i).getA();
             row[2] = flist.get(i).getB();
             row[3] = flist.get(i).getC();
             row[4] = flist.get(i).getD1();
             row[5] = flist.get(i).getD2();
             model.addRow(row); 
         }
    }
    
    public ArrayList<Feat> featList2(){
        ArrayList<Feat> featList2 = new ArrayList<Feat>();
        
        Connection cnct = dbconn.getConnection();
        Statement state = null;
        ResultSet resset;
        
        try{
            String sql = "SELECT dataset.img_id, dataset.img_name, data_feat.A, data_feat.B, data_feat.C, data_feat.D1, data_feat.D2 FROM dataset, data_feat WHERE dataset.img_id = data_feat.img_id ORDER BY dataset.img_name DESC";
            state = cnct.createStatement();
            resset = state.executeQuery(sql);
            Feat feat;
            
            while(resset.next()){
                feat = new Feat(resset.getInt("img_id"),resset.getString("img_name"),resset.getInt("A"),resset.getInt("B"),resset.getInt("C"),resset.getInt("D1"),resset.getInt("D2"));
                featList2.add(feat);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        return featList2;
    }
    
    public ArrayList<Feat> featList(int group, int purpose){
        ArrayList<Feat> featList = new ArrayList<Feat>();
        
        Connection cnct = dbconn.getConnection();
        Statement state = null;
        ResultSet resset;
        
        try{
            String sql = "SELECT dataset.img_id, dataset.img_name, data_feat.A, data_feat.B, data_feat.C, data_feat.D1, data_feat.D2 FROM dataset, data_feat WHERE dataset.img_id = data_feat.img_id AND dataset.img_grp = "+group+" AND dataset.purp_id = "+purpose+" ORDER BY dataset.img_id DESC";
            state = cnct.createStatement();
            resset = state.executeQuery(sql);
            Feat feat;
            
            while(resset.next()){
                feat = new Feat(resset.getInt("img_id"),resset.getString("img_name"),resset.getInt("A"),resset.getInt("B"),resset.getInt("C"),resset.getInt("D1"),resset.getInt("D2"));
                featList.add(feat);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        return featList;
    }
    
    public byte[] getImgBlob(int idimg){
        Connection cnct = dbconn.getConnection();
        PreparedStatement pstate = null;
        ResultSet resset = null;
        
        try{
            String sql = "SELECT img from dataset WHERE img_id = "+idimg;
            pstate = cnct.prepareStatement(sql);
            resset = pstate.executeQuery(sql);
            
            while(resset.next()){
                Blob imgblob = resset.getBlob("img");
                return imgblob.getBytes(1, (int) imgblob.length());
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        return null;
    }
    
    public int getgrpid(int choice){
        switch(choice){
            case 0: //Melanoma Dataset (Training)
                return 0;
            case 1: //Nevus Dataset (Training)
                return 1;
            case 2: //Seborrheic Keratosis Dataset (Training)
                return 2;
            case 3: //Melanoma Dataset (Testing)
                return 0;
            case 4: //Nevus Dataset (Testing)
                return 1;
            case 5: //Seborrheic Keratosis Dataset (Testing)
                return 2;
        }
        return -1;
    }
    
    public int getpurpid(int choice){
        switch(choice){
            case 0: //Melanoma Dataset (Training)
                return 0;
            case 1: //Nevus Dataset (Training)
                return 0;
            case 2: //Seborrheic Keratosis Dataset (Training)
                return 0;
            case 3: //Melanoma Dataset (Testing)
                return 1;
            case 4: //Nevus Dataset (Testing)
                return 1;
            case 5: //Seborrheic Keratosis Dataset (Testing)
                return 1;
        }
        return -1;
    }
    
    public void clear_table(){
        DefaultTableModel model = (DefaultTableModel)table_summary.getModel();
        model.setRowCount(0);
    }
    
    void setColor (JPanel a, JPanel b)
    {
        a.setBackground(new Color(132,131,113));
        b.setBackground(new Color(255,179,123));
    }
    
    void reset (JPanel a, JPanel b)
    {
        a.setBackground(new Color(93,91,87));
        b.setBackground(new Color(93,91,87));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultpstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DPrepTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DPrepTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DPrepTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DPrepTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DPrepTab().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel ImagePrev;
    private javax.swing.JPanel NavBar;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel11;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel22;
    private javax.swing.JPanel Panel3;
    private javax.swing.JPanel Panel33;
    private javax.swing.JPanel Panel4;
    private javax.swing.JPanel Panel44;
    private javax.swing.JPanel Panel5;
    private javax.swing.JPanel Panel55;
    private javax.swing.JPanel Specification;
    private javax.swing.JPanel Summary;
    private javax.swing.JPanel Task;
    private javax.swing.JPanel Title;
    private javax.swing.JButton btn_browse;
    private javax.swing.JButton btn_prepare;
    private javax.swing.JComboBox combo_grp;
    private javax.swing.JLabel imgpreview;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_username;
    private javax.swing.JTable table_summary;
    // End of variables declaration//GEN-END:variables
}
