/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Skylar Gail
 */
public class RGenTab extends javax.swing.JFrame {

    /**
     * Creates new form DatasetPreparationPage
     */
    public RGenTab() {
        initComponents();
        this.setLocationRelativeTo(null);
        reset(Panel1, Panel11);
        reset(Panel2,   Panel22);
        reset(Panel3,   Panel33);
        setColor(Panel4,   Panel44);
        reset(Panel5,   Panel55);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Task = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        Title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NavBar = new javax.swing.JPanel();
        Panel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Panel11 = new javax.swing.JPanel();
        Panel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Panel22 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        Panel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Panel33 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        Panel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Panel44 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        Panel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Panel55 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        ImagePrev = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);

        Task.setBackground(new java.awt.Color(191, 191, 191));

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("X");
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TaskLayout = new javax.swing.GroupLayout(Task);
        Task.setLayout(TaskLayout);
        TaskLayout.setHorizontalGroup(
            TaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaskLayout.createSequentialGroup()
                .addContainerGap(896, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        TaskLayout.setVerticalGroup(
            TaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskLayout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        Task.setBounds(0, 0, 970, 40);
        jLayeredPane1.add(Task, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Title.setBackground(new java.awt.Color(93, 91, 87));
        Title.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Admin Logo.png"))); // NOI18N
        Title.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 58, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CHAID for Skin Lesion");
        Title.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Classification");
        Title.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 161, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Admin Profile.png"))); // NOI18N
        Title.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 50, 60));

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("John Doe");
        Title.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 100, -1));

        Title.setBounds(0, 40, 970, 80);
        jLayeredPane1.add(Title, javax.swing.JLayeredPane.DEFAULT_LAYER);

        NavBar.setBackground(new java.awt.Color(93, 91, 87));
        NavBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel1.setBackground(new java.awt.Color(132, 131, 113));
        Panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel1MousePressed(evt);
            }
        });
        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Dataset Preparation");
        Panel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 37));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Icon DPrep.png"))); // NOI18N
        Panel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 4, 40, 50));

        Panel11.setBackground(new java.awt.Color(255, 179, 123));

        javax.swing.GroupLayout Panel11Layout = new javax.swing.GroupLayout(Panel11);
        Panel11.setLayout(Panel11Layout);
        Panel11Layout.setHorizontalGroup(
            Panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Panel11Layout.setVerticalGroup(
            Panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Panel1.add(Panel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        NavBar.add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 60));

        Panel2.setBackground(new java.awt.Color(93, 91, 87));
        Panel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel2MousePressed(evt);
            }
        });
        Panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("System Training");
        Panel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 37));

        Panel22.setBackground(new java.awt.Color(93, 91, 87));

        javax.swing.GroupLayout Panel22Layout = new javax.swing.GroupLayout(Panel22);
        Panel22.setLayout(Panel22Layout);
        Panel22Layout.setHorizontalGroup(
            Panel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Panel22Layout.setVerticalGroup(
            Panel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Panel2.add(Panel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Icon STest.png"))); // NOI18N
        Panel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 4, 40, 50));

        NavBar.add(Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 230, -1));

        Panel3.setBackground(new java.awt.Color(93, 91, 87));
        Panel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel3MousePressed(evt);
            }
        });
        Panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("System Testing");
        Panel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 37));

        Panel33.setBackground(new java.awt.Color(93, 91, 87));

        javax.swing.GroupLayout Panel33Layout = new javax.swing.GroupLayout(Panel33);
        Panel33.setLayout(Panel33Layout);
        Panel33Layout.setHorizontalGroup(
            Panel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Panel33Layout.setVerticalGroup(
            Panel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Panel3.add(Panel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Icon STrain.png"))); // NOI18N
        Panel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 4, 40, 50));

        NavBar.add(Panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 230, 60));

        Panel4.setBackground(new java.awt.Color(93, 91, 87));
        Panel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Report Genertion");
        Panel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 37));

        Panel44.setBackground(new java.awt.Color(93, 91, 87));

        javax.swing.GroupLayout Panel44Layout = new javax.swing.GroupLayout(Panel44);
        Panel44.setLayout(Panel44Layout);
        Panel44Layout.setHorizontalGroup(
            Panel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Panel44Layout.setVerticalGroup(
            Panel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Panel4.add(Panel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Icon RGen.png"))); // NOI18N
        Panel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 4, 40, 50));

        NavBar.add(Panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 230, 60));

        Panel5.setBackground(new java.awt.Color(93, 91, 87));
        Panel5.setAlignmentX(0.0F);
        Panel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel5MousePressed(evt);
            }
        });
        Panel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User Accounts");
        Panel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 37));

        Panel55.setBackground(new java.awt.Color(93, 91, 87));

        javax.swing.GroupLayout Panel55Layout = new javax.swing.GroupLayout(Panel55);
        Panel55.setLayout(Panel55Layout);
        Panel55Layout.setHorizontalGroup(
            Panel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Panel55Layout.setVerticalGroup(
            Panel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Panel5.add(Panel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Icon AMan.png"))); // NOI18N
        Panel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 4, 40, 50));

        NavBar.add(Panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 230, 60));

        NavBar.setBounds(0, 120, 240, 580);
        jLayeredPane1.add(NavBar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Body.setBackground(new java.awt.Color(255, 255, 255));
        Body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagePrev.setBackground(new java.awt.Color(93, 91, 87));
        ImagePrev.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        ImagePrev.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 35, 690, 400));

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Evaluation");
        ImagePrev.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        Body.add(ImagePrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 700, 440));

        jComboBox1.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CHAID Accuracy", "Success Rate 1st Feature", "Success Rate 2nd Feature", "Difference of Success Rates" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Body.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 300, 42));

        jButton3.setBackground(new java.awt.Color(241, 70, 78));
        jButton3.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Print");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Body.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 520, 100, 42));

        jButton4.setBackground(new java.awt.Color(255, 179, 123));
        jButton4.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jButton4.setText("Generate Report");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Body.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 144, 42));

        Body.setBounds(240, 120, 718, 574);
        jLayeredPane1.add(Body, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel2.setBackground(new java.awt.Color(93, 91, 87));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel2.setBounds(240, 695, 720, 3);
        jLayeredPane1.add(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.setBackground(new java.awt.Color(93, 91, 87));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.setBounds(959, 120, 3, 580);
        jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Panel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel5MousePressed
        new UAccTab().setVisible(true);
    }//GEN-LAST:event_Panel5MousePressed

    private void Panel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel3MousePressed
        new STestTab().setVisible(true);
    }//GEN-LAST:event_Panel3MousePressed

    private void Panel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel1MousePressed
        new DPrepTab().setVisible(true);
    }//GEN-LAST:event_Panel1MousePressed

    private void Panel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel2MousePressed
        new STrainTab().setVisible(true);
    }//GEN-LAST:event_Panel2MousePressed

    
    void setColor (JPanel a, JPanel b)
    {
        a.setBackground(new Color(132,131,113));
        b.setBackground(new Color(255,179,123));
    }
    
    void reset (JPanel a, JPanel b)
    {
        a.setBackground(new Color(93,91,87));
        b.setBackground(new Color(93,91,87));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RGenTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RGenTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RGenTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RGenTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RGenTab().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel ImagePrev;
    private javax.swing.JPanel NavBar;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel11;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel22;
    private javax.swing.JPanel Panel3;
    private javax.swing.JPanel Panel33;
    private javax.swing.JPanel Panel4;
    private javax.swing.JPanel Panel44;
    private javax.swing.JPanel Panel5;
    private javax.swing.JPanel Panel55;
    private javax.swing.JPanel Task;
    private javax.swing.JPanel Title;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
