package admin;

import java.awt.Color;
import java.sql.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import utilities.sqlcon;

public class UAccTab extends javax.swing.JFrame {
    sqlcon dbconn = new sqlcon();
    /**
     * Creates new form DatasetPreparationPage
     */
    public UAccTab() {
        initComponents();
        this.setLocationRelativeTo(null);
        reset(Panel1, Panel11);
        reset(Panel2,   Panel22);
        reset(Panel3,   Panel33);
        reset(Panel4,   Panel44);
        setColor(Panel5,   Panel55);
        showusersintable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Task = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        Title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NavBar = new javax.swing.JPanel();
        Panel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Panel11 = new javax.swing.JPanel();
        Panel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Panel22 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        Panel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Panel33 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        Panel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Panel44 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        Panel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Panel55 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        ImagePrev = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultsTable = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        field_ID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        field_fname = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        field_lname = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        field_uname = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        combo_accountype = new javax.swing.JComboBox();
        field_pword = new javax.swing.JTextField();
        DeleteButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        field_warning = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Task.setBackground(new java.awt.Color(191, 191, 191));

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("X");
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TaskLayout = new javax.swing.GroupLayout(Task);
        Task.setLayout(TaskLayout);
        TaskLayout.setHorizontalGroup(
            TaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaskLayout.createSequentialGroup()
                .addContainerGap(896, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        TaskLayout.setVerticalGroup(
            TaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskLayout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLayeredPane1.add(Task);
        Task.setBounds(0, 0, 970, 40);

        Title.setBackground(new java.awt.Color(93, 91, 87));
        Title.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Admin Logo.png"))); // NOI18N
        Title.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 58, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CHAID for Skin Lesion");
        Title.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Classification");
        Title.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 161, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Admin Profile.png"))); // NOI18N
        Title.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 50, 60));

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("John Doe");
        Title.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 100, -1));

        jLayeredPane1.add(Title);
        Title.setBounds(0, 40, 970, 80);

        NavBar.setBackground(new java.awt.Color(93, 91, 87));
        NavBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel1.setBackground(new java.awt.Color(132, 131, 113));
        Panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel1MousePressed(evt);
            }
        });
        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Dataset Preparation");
        Panel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 37));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Icon DPrep.png"))); // NOI18N
        Panel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 4, 40, 50));

        Panel11.setBackground(new java.awt.Color(255, 179, 123));

        javax.swing.GroupLayout Panel11Layout = new javax.swing.GroupLayout(Panel11);
        Panel11.setLayout(Panel11Layout);
        Panel11Layout.setHorizontalGroup(
            Panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Panel11Layout.setVerticalGroup(
            Panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Panel1.add(Panel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        NavBar.add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 60));

        Panel2.setBackground(new java.awt.Color(93, 91, 87));
        Panel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel2MousePressed(evt);
            }
        });
        Panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("System Training");
        Panel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 37));

        Panel22.setBackground(new java.awt.Color(93, 91, 87));

        javax.swing.GroupLayout Panel22Layout = new javax.swing.GroupLayout(Panel22);
        Panel22.setLayout(Panel22Layout);
        Panel22Layout.setHorizontalGroup(
            Panel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Panel22Layout.setVerticalGroup(
            Panel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Panel2.add(Panel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Icon STest.png"))); // NOI18N
        Panel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 4, 40, 50));

        NavBar.add(Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 230, -1));

        Panel3.setBackground(new java.awt.Color(93, 91, 87));
        Panel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel3MousePressed(evt);
            }
        });
        Panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("System Testing");
        Panel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 37));

        Panel33.setBackground(new java.awt.Color(93, 91, 87));

        javax.swing.GroupLayout Panel33Layout = new javax.swing.GroupLayout(Panel33);
        Panel33.setLayout(Panel33Layout);
        Panel33Layout.setHorizontalGroup(
            Panel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Panel33Layout.setVerticalGroup(
            Panel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Panel3.add(Panel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Icon STrain.png"))); // NOI18N
        Panel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 4, 40, 50));

        NavBar.add(Panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 230, 60));

        Panel4.setBackground(new java.awt.Color(93, 91, 87));
        Panel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel4MousePressed(evt);
            }
        });
        Panel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Report Genertion");
        Panel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 37));

        Panel44.setBackground(new java.awt.Color(93, 91, 87));

        javax.swing.GroupLayout Panel44Layout = new javax.swing.GroupLayout(Panel44);
        Panel44.setLayout(Panel44Layout);
        Panel44Layout.setHorizontalGroup(
            Panel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Panel44Layout.setVerticalGroup(
            Panel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Panel4.add(Panel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Icon RGen.png"))); // NOI18N
        Panel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 4, 40, 50));

        NavBar.add(Panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 230, 60));

        Panel5.setBackground(new java.awt.Color(93, 91, 87));
        Panel5.setAlignmentX(0.0F);
        Panel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel5MousePressed(evt);
            }
        });
        Panel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User Accounts");
        Panel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 37));

        Panel55.setBackground(new java.awt.Color(93, 91, 87));

        javax.swing.GroupLayout Panel55Layout = new javax.swing.GroupLayout(Panel55);
        Panel55.setLayout(Panel55Layout);
        Panel55Layout.setHorizontalGroup(
            Panel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Panel55Layout.setVerticalGroup(
            Panel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Panel5.add(Panel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Icon AMan.png"))); // NOI18N
        Panel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 4, 40, 50));

        NavBar.add(Panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 230, 60));

        jLayeredPane1.add(NavBar);
        NavBar.setBounds(0, 120, 240, 580);

        Body.setBackground(new java.awt.Color(255, 255, 255));
        Body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagePrev.setBackground(new java.awt.Color(93, 91, 87));
        ImagePrev.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ResultsTable.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        ResultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Username", "Account Type", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ResultsTable.setGridColor(new java.awt.Color(93, 91, 87));
        ResultsTable.setShowHorizontalLines(false);
        ResultsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResultsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ResultsTable);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 400));

        ImagePrev.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 35, 410, -1));

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Account Management");
        ImagePrev.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Account Details");
        ImagePrev.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("ID");

        field_ID.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("First Name");

        jLabel20.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Last Name");

        jLabel21.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Username");

        jLabel22.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Password");

        jLabel23.setFont(new java.awt.Font("Lucida Sans", 1, 11)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Account Type");

        combo_accountype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrative", "Non-administrative" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(field_lname)
                    .addComponent(field_fname)
                    .addComponent(field_ID)
                    .addComponent(field_uname)
                    .addComponent(combo_accountype, 0, 151, Short.MAX_VALUE)
                    .addComponent(field_pword))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_fname, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_lname, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_uname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_pword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_accountype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150))
        );

        ImagePrev.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 70, 260, 240));

        DeleteButton.setBackground(new java.awt.Color(204, 0, 0));
        DeleteButton.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Icon Delete.png"))); // NOI18N
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        ImagePrev.add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 110, 40));

        UpdateButton.setBackground(new java.awt.Color(255, 255, 255));
        UpdateButton.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        UpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Icon Edit.png"))); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        ImagePrev.add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 120, 40));

        AddButton.setBackground(new java.awt.Color(30, 144, 255));
        AddButton.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        AddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Icon Add.png"))); // NOI18N
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        ImagePrev.add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 130, 40));

        field_warning.setForeground(new java.awt.Color(255, 0, 0));
        field_warning.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        field_warning.setText("All fields should be filled out.");
        ImagePrev.add(field_warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 260, 30));

        Body.add(ImagePrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 700, 500));

        jTextField1.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        Body.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 40));

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin/Icon Search.png"))); // NOI18N
        Body.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 40, 40));

        jLayeredPane1.add(Body);
        Body.setBounds(240, 120, 718, 574);

        jPanel2.setBackground(new java.awt.Color(93, 91, 87));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jLayeredPane1.add(jPanel2);
        jPanel2.setBounds(240, 695, 720, 3);

        jPanel1.setBackground(new java.awt.Color(93, 91, 87));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jLayeredPane1.add(jPanel1);
        jPanel1.setBounds(959, 120, 3, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Panel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel5MousePressed
 
    }//GEN-LAST:event_Panel5MousePressed

    private void Panel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel3MousePressed
        new STestTab().setVisible(true);
    }//GEN-LAST:event_Panel3MousePressed

    private void Panel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel1MousePressed
        new DPrepTab().setVisible(true);
    }//GEN-LAST:event_Panel1MousePressed

    private void Panel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel2MousePressed
        new STrainTab().setVisible(true);
    }//GEN-LAST:event_Panel2MousePressed

    private void Panel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel4MousePressed
        new RGenTab().setVisible(true);
    }//GEN-LAST:event_Panel4MousePressed

    
    
    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        int strint = selectcombo(combo_accountype.getSelectedItem().toString());
        
        String query = "INSERT INTO user (f_name, l_name, u_name, status_id, password)"
                + " VALUES ('"+field_fname.getText()+"', '"+field_lname.getText()+
                "', '"+field_uname.getText()+"', '"+strint+"', '"+field_pword.getText()+"')";
        
        execute_sql_query(query, "added");
        
        clearFields();
        
        if(field_ID.getText().isEmpty()){
            execute_sql_query(query, "added");
            clearFields();
        }else{
            JOptionPane.showMessageDialog(null, "Select UPDATE button!");
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    public int selectcombo(String stritem){
        if(stritem.equals("Administrative")){
            return 0;
        }else if(stritem.equals("Non-administrative")){
            return 1;
        }
        return -1;
    }
    
    public boolean checkname(){
        
        return false;
    }
    
    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        int strint = selectcombo(combo_accountype.getSelectedItem().toString());
        
        String query = "UPDATE user SET f_name='"+field_fname.getText()+"', l_name='"+field_lname.getText()+"', u_name='"+field_uname.getText()
                +"', status_id="+strint+", password='"+field_pword.getText()+"' WHERE user_id = "+field_ID.getText();
        
        if(field_ID.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Select data from the table!");
            clearFields();
        }else{
            execute_sql_query(query, "updated");
            clearFields();
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

/*    */
    private void ResultsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultsTableMouseClicked
        // display selected row in fields
        int i = ResultsTable.getSelectedRow();
        TableModel model = ResultsTable.getModel();
        field_ID.setText(model.getValueAt(i,0).toString());
        field_fname.setText(model.getValueAt(i,1).toString());
        field_lname.setText(model.getValueAt(i,2).toString());
        field_uname.setText(model.getValueAt(i,3).toString());
        combo_accountype.setSelectedItem(model.getValueAt(i,4).toString());
        field_pword.setText(model.getValueAt(i,5).toString());
    }//GEN-LAST:event_ResultsTableMouseClicked

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        String query = "DELETE FROM user WHERE user_id ="+field_ID.getText();
        
        execute_sql_query(query, "deleted");
        
        clearFields();
    }//GEN-LAST:event_DeleteButtonActionPerformed
    
    public ArrayList<User> usersList(){
        ArrayList<User> usersList = new ArrayList<User>();
        
        Connection cnct = dbconn.getConnection();
        Statement state;
        ResultSet resset;
        
        String sql = "SELECT user.user_id, user.f_name, user.l_name, user.u_name, userstatus.stat_desc, user.password FROM user, userstatus WHERE user.status_id=userstatus.status_id";
        
        try{
            state = cnct.createStatement();
            resset = state.executeQuery(sql);
            User user;
            
            while(resset.next()){
                user = new User(resset.getInt("user_id"),resset.getString("f_name"),resset.getString("l_name"),
                        resset.getString("u_name"),resset.getString("stat_desc"),resset.getString("password"));
                usersList.add(user);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        return usersList;
    }
    
    //display data in table
    public void showusersintable(){
        ArrayList<User> list = usersList();
        DefaultTableModel model = (DefaultTableModel)ResultsTable.getModel(); 
         Object[] row = new Object[6];
         
         for(int i=0; i<list.size(); i++){
             row[0] = list.get(i).getUserId();
             row[1] = list.get(i).getFirstName();
             row[2] = list.get(i).getLastName();
             row[3] = list.get(i).getUserName();
             row[4] = list.get(i).getAccountype();
             row[5] = list.get(i).getPwd();
             
             model.addRow(row); 
         }
    }
    
    //execute the sql query
    public void execute_sql_query(String query, String message){
        Connection con = dbconn.getConnection();
        Statement state = null;
        
        try{
            state = con.createStatement();
            if(state.executeUpdate(query) == 1){
                //refresh table
                DefaultTableModel model= (DefaultTableModel)ResultsTable.getModel();
                model.setRowCount(0);
                showusersintable();
                JOptionPane.showMessageDialog(null, "Data "+message+" Successfully");
            }else{
                JOptionPane.showMessageDialog(null, "Data Not "+message);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    public void clearFields(){
        field_ID.setText("");
        field_fname.setText("");
        field_lname.setText("");
        field_uname.setText("");
        combo_accountype.setSelectedItem("Administrative");
        field_pword.setText("");
    }
    
    void setColor (JPanel a, JPanel b)
    {
        a.setBackground(new Color(132,131,113));
        b.setBackground(new Color(255,179,123));
    }
    
    void reset (JPanel a, JPanel b)
    {
        a.setBackground(new Color(93,91,87));
        b.setBackground(new Color(93,91,87));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UAccTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UAccTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UAccTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UAccTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UAccTab().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JPanel Body;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JPanel ImagePrev;
    private javax.swing.JPanel NavBar;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel11;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel22;
    private javax.swing.JPanel Panel3;
    private javax.swing.JPanel Panel33;
    private javax.swing.JPanel Panel4;
    private javax.swing.JPanel Panel44;
    private javax.swing.JPanel Panel5;
    private javax.swing.JPanel Panel55;
    private javax.swing.JTable ResultsTable;
    private javax.swing.JPanel Task;
    private javax.swing.JPanel Title;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JComboBox combo_accountype;
    private javax.swing.JTextField field_ID;
    private javax.swing.JTextField field_fname;
    private javax.swing.JTextField field_lname;
    private javax.swing.JTextField field_pword;
    private javax.swing.JTextField field_uname;
    private javax.swing.JLabel field_warning;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
